# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57584dd1eb0b32f6edd0705cf6917652835a3c69a9f62df8f7d9c5a0ea62f4318151f4cfbff7506bd5c5cd635165986a5bea9da6593d91d27c6ab97748a8d507

test:
  secret_key_base: bbb382a0f50ceeab4276fd5991863ae3b4846a1b87a19b6eb23ede77952db10f87dc5176fe6ccaa6edc7271b171845993d550ef2c9b3e341ca2a096fc2fd81d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
